// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(FUMiniHotelManagementDBContext))]
    partial class FUMiniHotelManagementDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessOjects.BookingDetail", b =>
                {
                    b.Property<int>("BookingReservationID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<decimal?>("ActualPrice")
                        .HasColumnType("money");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BookingReservationID", "RoomID");

                    b.HasIndex("RoomID");

                    b.ToTable("BookingDetail");

                    b.HasData(
                        new
                        {
                            BookingReservationID = 1,
                            RoomID = 3,
                            ActualPrice = 199.00m,
                            EndDate = new DateOnly(2024, 1, 2),
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            BookingReservationID = 1,
                            RoomID = 7,
                            ActualPrice = 179.00m,
                            EndDate = new DateOnly(2024, 1, 2),
                            StartDate = new DateOnly(2024, 1, 1)
                        },
                        new
                        {
                            BookingReservationID = 2,
                            RoomID = 3,
                            ActualPrice = 199.00m,
                            EndDate = new DateOnly(2024, 1, 6),
                            StartDate = new DateOnly(2024, 1, 5)
                        },
                        new
                        {
                            BookingReservationID = 2,
                            RoomID = 5,
                            ActualPrice = 219.00m,
                            EndDate = new DateOnly(2024, 1, 9),
                            StartDate = new DateOnly(2024, 1, 5)
                        });
                });

            modelBuilder.Entity("BusinessOjects.BookingReservation", b =>
                {
                    b.Property<int>("BookingReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingReservationID"));

                    b.Property<DateOnly?>("BookingDate")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<byte?>("BookingStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("money");

                    b.HasKey("BookingReservationID");

                    b.HasIndex("CustomerID");

                    b.ToTable("BookingReservation");

                    b.HasData(
                        new
                        {
                            BookingReservationID = 1,
                            BookingDate = new DateOnly(2023, 12, 20),
                            BookingStatus = (byte)1,
                            CustomerID = 3,
                            TotalPrice = 378.00m
                        },
                        new
                        {
                            BookingReservationID = 2,
                            BookingDate = new DateOnly(2023, 12, 21),
                            BookingStatus = (byte)1,
                            CustomerID = 3,
                            TotalPrice = 1493.00m
                        });
                });

            modelBuilder.Entity("BusinessOjects.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<DateOnly?>("CustomerBirthday")
                        .HasColumnType("date");

                    b.Property<string>("CustomerFullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("CustomerStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerID = 3,
                            CustomerBirthday = new DateOnly(1990, 2, 2),
                            CustomerFullName = "William Shakespeare",
                            CustomerStatus = (byte)1,
                            EmailAddress = "WilliamShakespeare@FUMiniHotel.org",
                            Password = "123@",
                            Telephone = "0903939393"
                        },
                        new
                        {
                            CustomerID = 5,
                            CustomerBirthday = new DateOnly(1991, 3, 3),
                            CustomerFullName = "Elizabeth Taylor",
                            CustomerStatus = (byte)1,
                            EmailAddress = "ElizabethTaylor@FUMiniHotel.org",
                            Password = "144@",
                            Telephone = "0903939377"
                        },
                        new
                        {
                            CustomerID = 8,
                            CustomerBirthday = new DateOnly(1992, 11, 10),
                            CustomerFullName = "James Cameron",
                            CustomerStatus = (byte)1,
                            EmailAddress = "JamesCameron@FUMiniHotel.org",
                            Password = "443@",
                            Telephone = "0903946582"
                        },
                        new
                        {
                            CustomerID = 9,
                            CustomerBirthday = new DateOnly(1991, 12, 5),
                            CustomerFullName = "Charles Dickens",
                            CustomerStatus = (byte)1,
                            EmailAddress = "CharlesDickens@FUMiniHotel.org",
                            Password = "563@",
                            Telephone = "0903955633"
                        },
                        new
                        {
                            CustomerID = 10,
                            CustomerBirthday = new DateOnly(1993, 12, 24),
                            CustomerFullName = "George Orwell",
                            CustomerStatus = (byte)1,
                            EmailAddress = "GeorgeOrwell@FUMiniHotel.org",
                            Password = "177@",
                            Telephone = "0913933493"
                        });
                });

            modelBuilder.Entity("BusinessOjects.RoomInformation", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<string>("RoomDetailDescription")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int?>("RoomMaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("RoomPricePerDay")
                        .HasColumnType("money");

                    b.Property<byte?>("RoomStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomTypeID");

                    b.ToTable("RoomInformation");

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            RoomDetailDescription = "A basic room with essential amenities, suitable for individual travelers or couples.",
                            RoomMaxCapacity = 3,
                            RoomNumber = "2364",
                            RoomPricePerDay = 149.00m,
                            RoomStatus = (byte)1,
                            RoomTypeID = 1
                        },
                        new
                        {
                            RoomID = 2,
                            RoomDetailDescription = "Deluxe rooms offer additional features such as a balcony or sea view, upgraded bedding, and improved décor.",
                            RoomMaxCapacity = 5,
                            RoomNumber = "3345",
                            RoomPricePerDay = 299.00m,
                            RoomStatus = (byte)1,
                            RoomTypeID = 3
                        },
                        new
                        {
                            RoomID = 3,
                            RoomDetailDescription = "A luxurious and spacious room with separate living and sleeping areas, ideal for guests seeking extra comfort and space.",
                            RoomMaxCapacity = 4,
                            RoomNumber = "4432",
                            RoomPricePerDay = 199.00m,
                            RoomStatus = (byte)1,
                            RoomTypeID = 2
                        },
                        new
                        {
                            RoomID = 5,
                            RoomDetailDescription = "Floor 3, Window in the North West",
                            RoomMaxCapacity = 5,
                            RoomNumber = "3342",
                            RoomPricePerDay = 219.00m,
                            RoomStatus = (byte)1,
                            RoomTypeID = 5
                        },
                        new
                        {
                            RoomID = 7,
                            RoomDetailDescription = "Floor 4, main window in the South",
                            RoomMaxCapacity = 4,
                            RoomNumber = "4434",
                            RoomPricePerDay = 179.00m,
                            RoomStatus = (byte)1,
                            RoomTypeID = 1
                        });
                });

            modelBuilder.Entity("BusinessOjects.RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TypeDescription")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TypeNote")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RoomTypeID");

                    b.ToTable("RoomType");

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            RoomTypeName = "Standard room",
                            TypeDescription = "This is typically the most affordable option and provides basic amenities such as a bed, dresser, and TV.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            RoomTypeName = "Suite",
                            TypeDescription = "Suites usually offer more space and amenities than standard rooms, such as a separate living area, kitchenette, and multiple bathrooms.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            RoomTypeName = "Deluxe room",
                            TypeDescription = "Deluxe rooms offer additional features such as a balcony or sea view, upgraded bedding, and improved décor.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 4,
                            RoomTypeName = "Executive room",
                            TypeDescription = "Executive rooms are designed for business travelers and offer perks such as free breakfast, evening drink, and high-speed internet.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 5,
                            RoomTypeName = "Family Room",
                            TypeDescription = "A room specifically designed to accommodate families, often with multiple beds and additional space for children.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 6,
                            RoomTypeName = "Connecting Room",
                            TypeDescription = "Two or more rooms with a connecting door, providing flexibility for larger groups or families traveling together.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 7,
                            RoomTypeName = "Penthouse Suite",
                            TypeDescription = "An extravagant, top-floor suite with exceptional views and exclusive amenities, typically chosen for special occasions or VIP guests.",
                            TypeNote = "N/A"
                        },
                        new
                        {
                            RoomTypeID = 8,
                            RoomTypeName = "Bungalow",
                            TypeDescription = "A standalone cottage-style accommodation, providing privacy and a sense of seclusion often within a resort setting",
                            TypeNote = "N/A"
                        });
                });

            modelBuilder.Entity("BusinessOjects.BookingDetail", b =>
                {
                    b.HasOne("BusinessOjects.BookingReservation", "BookingReservation")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessOjects.RoomInformation", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingReservation");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BusinessOjects.BookingReservation", b =>
                {
                    b.HasOne("BusinessOjects.Customer", "Customer")
                        .WithMany("BookingReservations")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessOjects.RoomInformation", b =>
                {
                    b.HasOne("BusinessOjects.RoomType", "RoomType")
                        .WithMany("RoomInformations")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("BusinessOjects.BookingReservation", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("BusinessOjects.Customer", b =>
                {
                    b.Navigation("BookingReservations");
                });

            modelBuilder.Entity("BusinessOjects.RoomInformation", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("BusinessOjects.RoomType", b =>
                {
                    b.Navigation("RoomInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
